// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.2.1
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18051
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AmazonWishlistTracker.Specs.Scraper
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.2.1")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ScraperMetaDataFetch")]
    public partial class ScraperMetaDataFetchFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ScraperMetaDataFetch.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ScraperMetaDataFetch", "In order to setup the scraping processfor my personal wishlist\r\nAs a screen scrap" +
                    "ing component\r\nI want to extract the list of wishlists from a wishlist page", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Prepare for book scraping")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void PrepareForBookScraping()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Prepare for book scraping", new string[] {
                        "mytag"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "AmazonTarget",
                        "Email"});
            table1.AddRow(new string[] {
                        "UK",
                        "alho@miguelalho.com"});
#line 8
 testRunner.Given("I have configured my scraper with:", ((string)(null)), table1, "Given ");
#line 11
 testRunner.When("I retrieve the users wishlists", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "wishlistName",
                        "wishlistPageId"});
            table2.AddRow(new string[] {
                        "Business",
                        "13WMOM3XTAK5G"});
            table2.AddRow(new string[] {
                        "Drawing",
                        "2G6OFE9P47AKA"});
            table2.AddRow(new string[] {
                        "Electronics",
                        "1BSEQ7U2E6RBE"});
            table2.AddRow(new string[] {
                        "Engeneering and business",
                        "2OPMME7SI9MPV"});
            table2.AddRow(new string[] {
                        "Fiction",
                        "39ACCHDMKVKJ1"});
            table2.AddRow(new string[] {
                        "Home and stuff",
                        "32BRN6BOWYVID"});
            table2.AddRow(new string[] {
                        "Methodologies",
                        "20E6BOWWE0J4T"});
            table2.AddRow(new string[] {
                        "New Wish List",
                        "2P8W7HDF4M6NR"});
            table2.AddRow(new string[] {
                        "Patterns",
                        "34GLJJOVRPDZU"});
            table2.AddRow(new string[] {
                        "Photography",
                        "2WYRZAFDXJ9C2"});
            table2.AddRow(new string[] {
                        "PRoductivity",
                        "1O0W0NU3ZPF1J"});
            table2.AddRow(new string[] {
                        "programming",
                        "2CCU7K0PHVBZ6"});
            table2.AddRow(new string[] {
                        "Psycology",
                        "22JADHUMCHCOZ"});
            table2.AddRow(new string[] {
                        "Training",
                        "MT9A2WI1FL61"});
            table2.AddRow(new string[] {
                        "Web and UI",
                        "10MTFE33315HU"});
            table2.AddRow(new string[] {
                        "Wish List",
                        "GKBVZ2B8F57P"});
#line 12
 testRunner.Then("the scraper should know that there are the following wishlists:", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
